package com.ihren.processor.constant;

public enum ErrorCode {
    CACHE_EXCEPTION,
    MAPPING_EXCEPTION,
    NOT_FOUND_EXCEPTION,
    SERIALIZATION_EXCEPTION,
    VALIDATION_EXCEPTION,
    UNKNOWN_EXCEPTION
}
