server:
  port: 8081
spring:
  application:
    name: processor
  cloud:
    function:
      definition: processTransaction;replayTransaction
    stream:
      default:
        consumer:
          use-native-decoding: true
        producer:
          use-native-encoding: true
      bindings:
        processTransaction-in-0:
          destination: transaction
          group: processTransaction
        processTransaction-out-0:
          destination: processed-transaction
        #TODO: when smth went wrong in here, will it will be sent to dlt?
        replayTransaction-in-0:
          destination: transaction.replay
          group: replayTransaction
#          TODO: is it worth it to manage state manually? (a lot of new code) (is there a solution for how to set state to STOPPED with a condition or so?)
#          consumer:
#            auto-startup: false
        replayTransaction-out-0:
          destination: processed-transaction
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
            spring.deserializer.value.delegate.class: com.ihren.processor.serializer.JsonDeserializer
            value.deserializer.target.class: com.ihren.processor.model.input.InputTransaction
          producer-properties:
            key.serializer: org.apache.kafka.common.serialization.StringSerializer
            value.serializer: com.ihren.processor.serializer.JsonSerializer
        bindings:
          processTransaction-in-0:
            consumer:
              enable-dlq: true
              dlq-name: transaction.dlt
              configuration:
                isolation:
                  level: read_committed
          replayTransaction-in-0:
            consumer:
              configuration:
                isolation:
                  level: read_committed
api:
  product:
    url: localhost:8080
cache:
  item:
    expiration: 1d