server:
  port: 8082
spring:
  application:
    name: consumer
  cloud:
    function:
      definition: consumePerson
    stream:
      bindings:
        consumePerson-in-0:
          destination: processed-people
          group: consumer
      default:
        consumer:
          use-native-decoding: true
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            value.deserializer: com.ihren.misc.serialization.PersonDeserializer