server:
  port: 8081
spring:
  cloud:
    function:
      definition: processPerson
    stream:
      default:
        consumer:
          use-native-decoding: true
        producer:
          use-native-encoding: true
      bindings:
        processPerson-in-0:
          destination: people
          group: processor
        processPerson-out-0:
          destination: processed-people
          group: consumer
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            value.deserializer: com.ihren.processor.serialization.PersonDeserializer
          producer-properties:
            value.serializer: com.ihren.processor.serialization.PersonSerializer
        bindings:
          processPerson-in-0:
            consumer:
              startOffset: earliest
              configuration:
                isolation:
                  level: read_committed