server:
  port: 8081
spring:
  application:
    name: processor
  cloud:
    function:
      definition: processTransaction
    stream:
      default:
        consumer:
          use-native-decoding: true
        producer:
          use-native-encoding: true
      bindings:
        processTransaction-in-0:
          destination: transaction
          group: processor
        processTransaction-out-0:
          destination: processed-transaction
      kafka:
        binder:
          brokers: localhost:9092
          consumer-properties:
            value.deserializer: com.ihren.processor.serialization.GenericDeserializer
            value.deserializer.target.class: com.ihren.processor.dto.TransactionDto
          producer-properties:
            value.serializer: com.ihren.processor.serialization.GenericSerializer
        bindings:
          processPerson-in-0:
            consumer:
              startOffset: earliest
              configuration:
                isolation:
                  level: read_committed