spring:
  cloud:
    stream:
      bindings:
        processTransaction-in-0:
          destination: test
        processTransaction-out-0:
          destination: processed-test
        replayTransaction-in-0:
          destination: test.replay
        replayTransaction-out-0:
          destination: processed-test
      kafka:
        bindings:
          processTransaction-in-0:
            consumer:
              dlq-name: test.dlt
          replayTransaction-in-0:
            consumer:
              dlq-name: test.dlt
