spring:
  cloud:
    stream:
      bindings:
        processTransaction-in-0:
          destination: test
        processTransaction-out-0:
          destination: processed-test
        reprocessTransaction-in-0:
          destination: test.replay
        reprocessTransaction-out-0:
          destination: processed-test