spring:
  cloud:
    stream:
      bindings:
        processPerson-in-0:
          destination: people-test
          group: processor-test
        processPerson-out-0:
          destination: processed-people-test
          group: consumer-test