spring:
  cloud:
    stream:
      bindings:
        processTransaction-in-0:
          destination: test
          group: processor-test
        processTransaction-out-0:
          destination: processed-test