spring:
  cloud:
    stream:
      bindings:
        processPerson-in-0:
          destination: people
          group: consumer
        processPerson-out-0:
          destination: processed-people
          group: consumer
      default:
        consumer:
          use-native-decoding: true
        producer:
          use-native-encoding: true
      kafka:
        binder:
          consumer-properties:
            value.deserializer: com.ihren.misc.serialization.PersonDeserializer
          producer-properties:
            value.serializer: com.ihren.misc.serialization.PersonSerializer