server:
  port: 8080
spring:
  cloud:
    function:
      definition: producePerson
    stream:
      bindings:
        producePerson-out-0:
          destination: people
      default:
        producer:
          use-native-encoding: true
      kafka:
        binder:
          brokers: localhost:9092
          producer-properties:
            value.serializer: com.ihren.misc.serialization.PersonSerializer
  integration:
    poller:
      fixed-delay: 5000