server:
  port: 8080
spring:
  application.name: producer
  cloud:
    stream:
      bindings:
        producePerson-out-0:
          destination: people
          group: consumer
          producer:
            use-native-encoding: true
      kafka:
        binder:
          brokers: localhost:9092
          producer-properties:
            value.serializer: com.ihren.misc.serialization.PersonSerializer
  integration:
    poller:
      fixed-delay: 5000